export const SHOW_HOVER_MENU = "SHOW_HOVER_MENU";
export const HIDE_HOVER_MENU = "HIDE_HOVER_MENU";

export const SHOW_PROFILE = "SHOW_PROFILE";
export const HIDE_PROFILE = "HIDE_PROFILE";

export const SHOW_MOBILE_SIDEBAR = "SHOW_MOBILE_SIDEBAR";
export const HIDE_MOBILE_SIDEBAR = "HIDE_MOBILE_SIDEBAR";

export const SET_MENU_CATEGORY = "SET_MENU_CATEGORY";
