export const SET_CATEGORIES = "SET_CATEGORIES";
export const SET_CATEGORY = "SET_CATEGORY";
export const SET_MAIN_CATEGORY = "SET_MAIN_CATEGORY";
export const SET_PAGE_CATEGORY = "SET_PAGE_CATEGORY";
