export const SET_CATEGORY_OPTIONS = "SET_CATEGORY_OPTIONS";
export const SET_BRAND_OPTIONS = "SET_BRAND_OPTIONS";
export const SET_COLOR_OPTIONS = "SET_COLOR_OPTIONS";
export const SET_SIZE_OPTIONS = "SET_SIZE_OPTIONS";
export const SET_CONDITION_OPTIONS = "SET_CONDITION_OPTIONS";
export const SET_MATERIAL_OPTIONS = "SET_MATERIAL_OPTIONS";
export const SET_QUERY = "SET_QUERY";
